// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoaerikekenopziclqjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvYWVyaWtla2Vub3B6aWNscWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjMyMjYsImV4cCI6MjA3NDEzOTIyNn0.zLee0H9gRco45XVeaORoBU-IigTiA_xrNb3mYf4fYyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});